export const cardList = [
  {
    id: 1,
    theme: "Web Design",
    title: "Разработать главный экран",
    date: "30.10.23",
    status: "Без статуса",
  },
  {
    id: 2,
    theme: "Research",
    title: "Исследовать конкурентов",
    date: "15.11.23",
    status: "Без статуса",
  },
  {
    id: 3,
    theme: "Copywriting",
    title: "Написать тексты для карточек",
    date: "05.12.23",
    status: "Без статуса",
  },
  {
    id: 4,
    theme: "Web Design",
    title: "Создать прототип в Figma",
    date: "20.10.23",
    status: "Нужно сделать",
  },
  {
    id: 5,
    theme: "Research",
    title: "Анализ целевой аудитории",
    date: "25.11.23",
    status: "Нужно сделать",
  },
  {
    id: 6,
    theme: "Web Design",
    title: "Вёрстка главной страницы",
    date: "10.11.23",
    status: "В работе",
  },
  {
    id: 7,
    theme: "Copywriting",
    title: "SEO-оптимизация текстов",
    date: "01.12.23",
    status: "В работе",
  },
  {
    id: 8,
    theme: "Web Design",
    title: "Тестирование на мобильных",
    date: "18.11.23",
    status: "Тестирование",
  },
  {
    id: 9,
    theme: "Research",
    title: "Сбор обратной связи",
    date: "28.11.23",
    status: "Тестирование",
  },
  {
    id: 10,
    theme: "Web Design",
    title: "Исправить баги",
    date: "05.12.23",
    status: "Готово",
  },
];